<?php
/*******************************************************************************************
*   ___  _          ______                     _ _                _                        *
*  / _ \| |         | ___ \                   | (_)              | |              © 2026   *
* / /_\ | | _____  _| |_/ /_ __ __ _ _ __   __| |_ _ __   __ _   | |_ ___  __ _ _ __ ___   *
* |  _  | |/ _ \ \/ / ___ \ '__/ _` | '_ \ / _` | | '_ \ / _` |  | __/ _ \/ _` | '_ ` _ \  *
* | | | | |  __/>  <| |_/ / | | (_| | | | | (_| | | | | | (_| |  | ||  __/ (_| | | | | | | *
* \_| |_/_|\___/_/\_\____/|_|  \__,_|_| |_|\__,_|_|_| |_|\__, |  \___\___|\__,_|_| |_| |_| *
*                                                         __/ |                            *
*                                                        |___/                             *
* ---------------------------------------------------------------------------------------- *
* This is commercial software, only users who have purchased a valid license and accept    *
* to the terms of the License Agreement can install and use this program.                  *
* ---------------------------------------------------------------------------------------- *
* website: https://cs-cart.alexbranding.com                                                *
*   email: info@alexbranding.com                                                           *
*******************************************************************************************/
$schema['vendor'] = [
'position' => 600,
'items' => [
'vendor_info' => [
'position' => 100,
'is_group' => 'Y',
'items' => [
'background' => [
'is_for_all_devices' => 'Y',
'type' => 'colorpicker',
'position' => 100,
'value' => '',
'value_styles' => [
'Black.less' => '#1e1e1e',
'Blue.less' => '#d9f5ff',
'Brick.less' => '#f5f5f7',
'Cobalt.less' => '#f5f5f7',
'Dark_Blue.less' => '#24488e',
'Dark_Navy.less' => '#4a5259',
'Default.less' => '#f5f5f7',
'Fiolent.less' => '#f5f5f7',
'Flame.less' => '#f5f5f7',
'Gray.less' => '#f5f5f7',
'Green.less' => '#f5f5f7',
'Indigo.less' => '#00ac89',
'Ink.less' => '#f5f5f7',
'Lime_dark.less' => '#2e2e2c',
'Malachite.less' => '#1e1e1e',
'Malachite_dark.less' => '#2e2e2e',
'Mint.less' => '#f5f5f7',
'Orange.less' => '#1e905d',
'Orange_dark.less' => '#171717',
'Original.less' => '#f5f5f7',
'Powder.less' => '#f5f5f7',
'Purple.less' => '#f5f5f7',
'Purple_dark.less' => '#30363d',
'Skyfall.less' => '#f5f5f7',
'Velvet.less' => '#f5f5f7',
'White.less' => '#f5f5f7',
],
],
'font_main' => [
'is_for_all_devices' => 'Y',
'type' => 'colorpicker',
'position' => 200,
'value' => '',
'value_styles' => [
'Black.less' => '#ffffff',
'Blue.less' => '#1e1e1e',
'Brick.less' => '#1e1e1e',
'Cobalt.less' => '#1e1e1e',
'Dark_Blue.less' => '#191b1e',
'Dark_Navy.less' => '#191b1e',
'Default.less' => '#363636',
'Fiolent.less' => '#1e1e1e',
'Flame.less' => '#1e1e1e',
'Gray.less' => '#212121',
'Green.less' => '#2e2e2e',
'Indigo.less' => '#333333',
'Ink.less' => '#333333',
'Mint.less' => '#2a2c30',
'Original.less' => '#ffffff',
'Orange.less' => '#ffffff',
'Powder.less' => '#f67055',
'Purple.less' => '#000000',
'Skyfall.less' => '#000000',
'Velvet.less' => '#333333',
'White.less' => '#1e1e1e',
],
],
'font_additional' => [
'is_for_all_devices' => 'Y',
'type' => 'colorpicker',
'position' => 300,
'value' => '',
'value_styles' => [
'Black.less' => '#999999',
'Blue.less' => '#677d87',
'Brick.less' => '#777777',
'Cobalt.less' => '#919191',
'Dark_Blue.less' => '#848c99',
'Dark_Navy.less' => '#848c99',
'Default.less' => '#8f8f8f',
'Fiolent.less' => '#919191',
'Flame.less' => '#777777',
'Gray.less' => '#888888',
'Green.less' => '#7b7b7b',
'Indigo.less' => '#8c8c8c',
'Ink.less' => '#8c8c8c',
'Mint.less' => '#7e848e',
'Original.less' => '#b2d6d7',
'Orange.less' => '#d0ece0',
'Powder.less' => '#f67055',
'Purple.less' => '#737373',
'Skyfall.less' => '#737373',
'Velvet.less' => '#8c8c8c',
'White.less' => '#919191',
],
],
'links' => [
'is_for_all_devices' => 'Y',
'type' => 'colorpicker',
'position' => 400,
'value' => '',
'value_styles' => [
'Black.less' => '#ffffff',
'Blue.less' => '#105990',
'Brick.less' => '#00bcd4',
'Cobalt.less' => '#0563d0',
'Dark_Blue.less' => '#24488e',
'Dark_Navy.less' => '#00bcd4',
'Default.less' => '#07c',
'Fiolent.less' => '#4651a7',
'Flame.less' => '#00a3cb',
'Gray.less' => '#039be5',
'Green.less' => '#3e77aa',
'Indigo.less' => '#7d568f',
'Ink.less' => '#428bca',
'Mint.less' => '#57a4a5',
'Original.less' => '#ffffff',
'Orange.less' => '#ffffff',
'Powder.less' => '#f67055',
'Purple.less' => '#01beac',
'Skyfall.less' => '#10b9e4',
'Velvet.less' => '#c90',
'White.less' => '#a1497e',
],
],
],
],
'vendor_menu' => [
'position' => 200,
'is_group' => 'Y',
'items' => [
'background' => [
'is_for_all_devices' => 'Y',
'type' => 'colorpicker',
'position' => 100,
'value' => '',
'value_styles' => [
'Black.less' => '#ffffff',
'Blue.less' => '#ffffff',
'Brick.less' => '#ea5920',
'Cobalt.less' => '#007aff',
'Dark_Blue.less' => '#ffffff',
'Dark_Navy.less' => '#ffffff',
'Default.less' => '#ffde03',
'Fiolent.less' => '#4651a7',
'Flame.less' => '#be0318',
'Gray.less' => '#ffffff',
'Green.less' => '#00a046',
'Indigo.less' => '#1dbc9b',
'Ink.less' => '#1d365d',
'Mint.less' => '#9ee0e1',
'Original.less' => '#363636',
'Orange.less' => '#ff6800',
'Powder.less' => '#f67055',
'Purple.less' => '#3700b3',
'Skyfall.less' => '#ffffff',
'Velvet.less' => '#666666',
'White.less' => '#ffffff',
],
],
'active_background' => [
'is_for_all_devices' => 'Y',
'type' => 'colorpicker',
'position' => 200,
'value' => '',
'value_styles' => [
'Black.less' => '#000000',
'Blue.less' => '#f6f6f6',
'Brick.less' => '#dc4d15',
'Cobalt.less' => '#0563d0',
'Dark_Blue.less' => '#f3f4f7',
'Dark_Navy.less' => '#f5f5f7',
'Default.less' => '#fad42b',
'Fiolent.less' => '#3e4895',
'Flame.less' => '#a50315',
'Gray.less' => '#e5e5e5',
'Green.less' => '#00913f',
'Indigo.less' => '#17a285',
'Ink.less' => '#182b4a',
'Mint.less' => '#88d2d3',
'Original.less' => '#2b2b2b',
'Orange.less' => '#f45a01',
'Powder.less' => '#f67055',
'Purple.less' => '#6200ee',
'Skyfall.less' => '#eeeeee',
'Velvet.less' => '#595959',
'White.less' => '#f6f6f6',
],
],
'item' => [
'is_for_all_devices' => 'Y',
'type' => 'colorpicker',
'position' => 300,
'value' => '',
'value_styles' => [
'Black.less' => '#1e1e1e',
'Blue.less' => '#1e1e1e',
'Brick.less' => '#ffffff',
'Cobalt.less' => '#ffffff',
'Dark_Blue.less' => '#191b1e',
'Dark_Navy.less' => '#191b1e',
'Default.less' => '363636',
'Fiolent.less' => '#ffffff',
'Flame.less' => '#ffffff',
'Gray.less' => '#212121',
'Green.less' => '#ffffff',
'Indigo.less' => '#ffffff',
'Ink.less' => '#ffffff',
'Mint.less' => '#2f353e',
'Original.less' => '#ffffff',
'Orange.less' => '#ffffff',
'Powder.less' => '#f67055',
'Purple.less' => '#ffffff',
'Skyfall.less' => '#000000',
'Velvet.less' => '#ffffff',
'White.less' => '#2e2e2e',
],
],
'item_active' => [
'is_for_all_devices' => 'Y',
'type' => 'colorpicker',
'position' => 400,
'value' => '',
'value_styles' => [
'Black.less' => '#ffffff',
'Blue.less' => '#1e1e1e',
'Brick.less' => '#ffffff',
'Cobalt.less' => '#ffffff',
'Dark_Blue.less' => '#191b1e',
'Dark_Navy.less' => '#191b1e',
'Default.less' => '363636',
'Fiolent.less' => '#ffffff',
'Flame.less' => '#ffffff',
'Gray.less' => '#212121',
'Green.less' => '#ffffff',
'Indigo.less' => '#ffffff',
'Ink.less' => '#ffffff',
'Mint.less' => '#2f353e',
'Original.less' => '#ffffff',
'Orange.less' => '#ffffff',
'Powder.less' => '#f67055',
'Purple.less' => '#ffffff',
'Skyfall.less' => '#000000',
'Velvet.less' => '#ffffff',
'White.less' => '#1e1e1e',
],
],
],
],
],
];
return $schema;
